### ISSUE TITLE
Incoming Packets not entering bess pipeline

### ISSUE THREAD

**Issue by aleemgsl** [omec-project/bess#38]
Hi Team,

We have deployed omec UPF (bess) pod as a part of 4G core deployment. We are using ipvlan (on access) and host-device (on Gi) plugins.
We see that traffic from enb goes to the UPF access interface enters Bess pipeline and goes out to the internet from the core interface. Downlink traffic from the Internet comes to the Gi interface and enters the bess pipeline CoreFast, and goes to Enb via the access interface.

We do not see any issue for a few days ( like 15-20 days approx), and then UPF stops processing packets. Packets are reaching access and core interfaces of UPF but are not entering the Bess pipeline.

There is no container restart/crash.

The issue gets resolved after the UPF pod is restarted.

Has anyone faced this issue before?

**Comment by sureshmarikkannu** [comment]
Please find below the investigation summary from the logs shared for this issue.

- In this setup AiaB deployed in 4G mode with ~20 UE's connected and sending significant amount of traffic (~2TB per day)
- AiaB deployed in a VM which is created in NUC server with NIC interfaces are configured using ESXi and attached to the VM's
- access and core interfaces configured as ipvlan and host-device cni plugins respectively
		cniPlugin: ipvlan
		cniPlugin1: host-device
- In UPF the measure_flow/measure_upf flags are enabled. We do have known packet drop issues when we enable measure_upf flag and configure UPF with more threads (more than 1 threads). However in this setup the number of cores configured for upf is 1, so above mentioned issue should not create any issues.
- The issues happens randomly after some time (sometime in few days and some time in couple of weeks)
- when the issue happens we confirmed that there is no packet received in UPF pipeline(verified via GUI).also we dont see the port status also not reporting any reception/drop of packets in the access/core interfaces. we verified it using below command,
	kubectl -n omec exec -ti upf-0 -- bessctl
	show port  
- we captured the packets inside upf pod using below command and we are able to see the packets on core/access interfaces,
	kubectl -n omec exec -ti upf-0 bessd -- tcpdump -i access -w access.pcap
	kubectl -n omec exec -ti upf-0 bessd -- tcpdump -i core -w core.pcap

- verified bessd/arping/dmesg logs for any potential issues. We dont see any info/error related to this issue.
	occasionally we see large size packets received (not frequent though) as follows,
		[10670850.338765] packet size is too long (1530 > 1518)
		[10670850.725224] packet size is too long (1530 > 1518)
- we do see below warning messages in bess logs,
	09:50:09.281783    93 flow_measure.cc:102] Encountered invalid flag: 18446744071298992138
	09:50:33.535010    93 flow_measure.cc:102] Encountered invalid flag: 18446744071449987082

	As mentioned earlier we don't have solid evidence that this might be causing any such issues. However if its possible we can disable these flags and see if we see these issues again.	At least we can disable measure_upf flag to see the behavior.

I have attached the collected logs for reference here. These logs are captured when the issue occurred in the system.

In parallel, we tried to reproduce this issue in local environment as follows,
	Deployed AiaB in 4G mode in baremetal server (NO VM's) and setup Trex traffic generator against the UPF. Control sessions are installed using the pfcp simulation interface. Then we pump traffic (~600Mbps) continuously to the UPF and see the behavior. We run these tests for very long period of time (~3-4 days), so far we don't see any issues in this environment.
	
we can try following options if possible,

1. Disable measure_upf flag in the deployment
2. Try to use normal servers (instead of VM's/ESXi, etc...) and see if we can observe similar issues.
[AF_PKT_No_pkt_4G_UPF.zip](https://github.com/omec-project/bess/files/14448443/AF_PKT_No_pkt_4G_UPF.zip)

**Comment by gab-arrobo** [comment]
@aleemgsl, as @sureshmarikkannu indicated we have not been able to observe the same issue in our setup. However, due to the specifics of your setup, we cannot fully replicate it. My suggestion is for you to create a new image incorporating the changes proposed in #39 (As you can see in the comments, a couple different issues have been resolved with this new patch)

**Comment by gab-arrobo** [comment]
Hi @aleemgsl, any feedback about this? Did you have a chance to give it a try to BESS latest version. Please let us know. Thanks!

**Comment by aleemgsl** [comment]
Hi @gab-arrobo Not yet. Due to the unavailability of the test setup, we could not start it. We will be starting it this week. We will update you.

**Comment by aleemgsl** [comment]
Hi @gab-arrobo,

We have upgraded dpdk version to 22.11 and tested it. We still see the problem. 

One observation I have:

Just before UPF goes into the stuck state, a DNS query is received from one UE with source port 2152 and destination port 53 (the source port used by UE is same as GTP-U port). These packets are sent to the internet and a response is received. This response (destination port 2152) is dropped by UPF and going to PDRlookup fail. This happens three times as DNS packet is retransmitted by UE and then issue appears i.e UPF stuck. I see this behavior in the last 3 occurrences. 

Can you please check if this has anything to do with the UPF going into the stuck state?

**Comment by aleemgsl** [comment]
Hi @gab-arrobo 

I can reproduce this issue in our lab by sending a DNS query from the laptop (accessing the internet via Edge) by using port 2152 as the source port. After few retries UPF is stuck.

**Comment by sureshmarikkannu** [comment]
@aleemgsl , Thanks for the logs and details on the reproduction steps. Please note that in my setup i tried to change the src/dst ports to 2152 for the DL packet and inner UL packet, in this case the DL packets getting dropped at the UPF similar to your setup, however i dont see the issue (packets suddenly stop coming to the UPF itself) which we see in your setup. However, i did went through the code flow for the malfunctioning packet traversal and want to try below patch in your environment to see if this helps us in resolving this issue. Can you please try this and let me know your observation,

diff --git a/core/modules/gtpu_parser.cc b/core/modules/gtpu_parser.cc
index d988fa0c..3261d582 100644
--- a/core/modules/gtpu_parser.cc
+++ b/core/modules/gtpu_parser.cc
@@ -70,7 +70,8 @@ void GtpuParser::ProcessBatch(Context *ctx, bess::PacketBatch *batch) {
         break;
       case Ipv4::kUdp:
         udph = (Udp *)((char *)iph + (iph->header_length << 2));
-        if (udph->dst_port == (be16_t)(UDP_PORT_GTPU)) {
+        if (udph->dst_port == (be16_t)(UDP_PORT_GTPU) &&
+           udph->src_port == (be16_t)(UDP_PORT_GTPU)) {
           Ipv4 *old_iph = iph;
           gtph = (Gtpv1 *)(udph + 1);
           be32_t teid = (be32_t)gtph->teid.value();

**Comment by aleemgsl** [comment]
@sureshmarikkannu Thanks for the quick fix. We have added the fix. And it looks good. We will do more testing and will update you.

**Comment by sureshmarikkannu** [comment]
Thanks a lot for your support @aleemgsl .

**Comment by aleemgsl** [comment]
Resolved
